language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
script:
  - ./test_set_trace.sh
  - coverage run --source=pyrs -m unittest discover pyrs -v
  - flake8 pyrs/
after_success:
  coveralls
